export const initialData = [
  {
    id: 1,
    type: 'number',
    valueNumber: 'firstValue',
    mask: null,
    multiline: false,
    placeholder: 'Number type',
    options: null,
    style: { width: '100%' },
  },
  {
    id: 2,
    type: 'text',
    valueNumber: 'secondValue',
    mask: null,
    multiline: false,
    placeholder: 'Text type',
    options: null,
    style: { width: '100%' },
  },
  {
    id: 3,
    type: 'text',
    valueNumber: 'thirdValue',
    mask: null,
    multiline: true,
    placeholder: 'Text multiline type',
    options: null,
    style: { width: '100%' },
  },
  {
    id: 4,
    type: 'text',
    valueNumber: 'fourValue',
    mask: '111-111',
    multiline: false,
    placeholder: 'With mask',
    options: null,
    style: {
      width: '100%',
      backgroundColor: 'white',
      color: 'black',
      borderRadius: '15px',
    },
  },
  {
    id: 5,
    type: 'text',
    valueNumber: 'fiveValue',
    mask: null,
    multiline: false,
    placeholder: 'Another type',
    options: [
      { value: 'first element', label: 'first element' },
      { value: 'second element', label: 'second element' },
      { value: 'third element', label: 'third element' },
    ],
    style: {
      width: '100%',
      backgroundColor: 'white',
      color: 'black',
      borderRadius: '15px',
    },
  },
];

export const initialValues = {
  firstValue: '',
  secondValue: '',
  thirdValue: '',
  fourValue: '',
  fiveValue: '',
};
